# Databricks notebook source
# MAGIC %md
# MAGIC # orders
# MAGIC Incrementally load orders into Silver keeping the newest record per order_id
# MAGIC
# MAGIC Layer: silver - strategy: dedup_latest - sources: orders - keys: order_id
# MAGIC
# MAGIC Generated by agentic-pipeline-copilot from a plan checked against the catalog.

# COMMAND ----------

# DBTITLE 1,Parameters
dbutils.widgets.text("orders_table", "")
dbutils.widgets.text("target_table", "")
dbutils.widgets.text("watermark", "")
dbutils.widgets.text("key_columns", "")
orders_table = dbutils.widgets.get("orders_table")
target_table = dbutils.widgets.get("target_table")
watermark = dbutils.widgets.get("watermark")
key_columns = dbutils.widgets.get("key_columns")

# COMMAND ----------

# DBTITLE 1,Read incremental orders batch with watermark
# Follows: pattern:module.transform-silver, table:orders, standard:notebook.explicit-schemas-and-column-lists, standard:notebook.configuration-comes-from-metadata-never-literals
from pyspark.sql import functions as F

watermark_epoch = int(watermark) if watermark else 0

source_cols = [
    "order_id",
    "customer_id",
    "order_status",
    "purchased_at",
    "delivered_at",
    "updated_at",
]

bronze_orders = (
    spark.read.table(orders_table)
    .select(*[F.col(c) for c in source_cols])
    .filter(F.col("updated_at").cast("long") >= watermark_epoch)
)

# COMMAND ----------

# DBTITLE 1,Deduplicate orders batch keeping the latest update per order_id
# Follows: pattern:module.transform-silver, standard:notebook.silver-keeps-one-current-row-per-key, standard:notebook.configuration-comes-from-metadata-never-literals, standard:notebook.quality-rules-run-before-writes
from pyspark.sql.window import Window

keys = [k.strip() for k in key_columns.split(",")]

window_spec = Window.partitionBy(*[F.col(k) for k in keys]).orderBy(F.col("updated_at").desc())

deduped_orders = (
    bronze_orders
    .withColumn("_row_num", F.row_number().over(window_spec))
    .filter(F.col("_row_num") == 1)
    .drop("_row_num")
)

# COMMAND ----------

# DBTITLE 1,Merge deduplicated orders into Silver target table
# Follows: pattern:module.transform-silver, table:orders, standard:notebook.writes-are-idempotent, standard:notebook.configuration-comes-from-metadata-never-literals, standard:notebook.no-unbounded-collect-or-topandas
from delta.tables import DeltaTable

target_delta = DeltaTable.forName(spark, target_table)
keys = [k.strip() for k in key_columns.split(",")]

merge_condition = " AND ".join([f"target.{k} = source.{k}" for k in keys])

(
    target_delta.alias("target")
    .merge(
        deduped_orders.alias("source"),
        merge_condition
    )
    .whenMatchedUpdateAll()
    .whenNotMatchedInsertAll()
    .execute()
)
